project:
  type: website
  output-dir: docs

website:
  title: "Ana Jaramillo's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - TidyTuesdays.qmd

format:
  html:
    theme: 
     light: morph
     dark: slate
    css: styles.css
    toc: true
    page-layout: full

editor: visual

