project:
  type: website
  output-dir: docs

website:
  title: "Ana Jaramillo's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Resume.qmd
        text: Resume
      - text: Data Viz
        menu: 
          - href: TT1.qmd
            text: "Numbat Plots"
          - href: TT2.qmd
            text: "Egg Production Plots"
          - href: Mini Project 2.qmd
            text: "Analyzing The Office Lines"
          - href: Mini Project 3.qmd
            text: "Real Estate Simulation"
          - href: Mini Project 4.qmd
            text: "SQL Data Analysis"

format:
  html:
    theme: 
     light: morph
     dark: slate
    css: styles.css
    toc: true
    page-layout: full

editor: visual

