---
title: "About"
---

# About Me

Hello! I'm Ana Jaramillo, a dedicated Biology major and Mathematics & Statistics minor at Pomona College. I am deeply interested in the scientific research process, but have started to focus my research specialty on data analysis and computational biology. I've developed statistical models, analyzed large genomic datasets, and collaborated across disciplines to uncover insights into complex biological systems–such as discovering drug targets for parasitic diseases and differential bacterial/fungal microbial analyses. Through my work, I aim to bridge the worlds of computation and biological research, uncovering new knowledge and contributing to meaningful change in healthcare and genomic computational biology.

## Current Projects

I am currently working on a research manuscript for my senior thesis, which I hope to publish upon completion. My project focuses on investigating differential microbial assemblages in the soil beneath five native California sagescrub plant species. This research explores the microbial diversity unique to each plant species and investigates how proximity to urban boundaries—an aspect known as the "edge effect"—influences the composition of these microbial communities. By examining edge and central soil samples, I aim to uncover how human-influenced environmental factors might alter microbial ecosystems in these natural settings.

To achieve this, I am conducting a bioinformatics analysis on the genomic data of both fungal and bacterial assemblages. Working with tools such as Jupyter Notebook and Python, I process and analyze large genomic datasets to identify patterns and draw meaningful insights. This analysis involves a variety of computational techniques, including data cleaning, genomic sequencing alignment, and community composition visualization, providing me with hands-on experience in advanced bioinformatics workflows.

## Research Experience

-   **University of Melbourne Bioinformatics Research Project**\
    As a research intern, I immersed myself in a project that examined gene expression patterns in *Schistosoma haematobium*, a parasitic organism with significant health impacts in endemic regions. This experience challenged me to bridge my biological knowledge with computational analysis, as I developed and implemented over 12 statistical models in R to interpret and visualize genomic data for over 10,000 sequences. I used the HISAT2 alignment program on the Galaxy platform to map gene expression levels across sex chromosomes, an innovative approach that broadened my understanding of bioinformatics workflows. Working alongside graduate and Ph.D. researchers, I gained firsthand experience in interdisciplinary collaboration, where I learned to refine protocols, troubleshoot data issues, and maintain data accuracy across large datasets. Presenting our findings at an international symposium was a transformative moment, teaching me to distill complex data insights into accessible, impactful narratives for a diverse scientific audience.

-   **Summer Undergraduate Research Program at Pomona College**\
    This research experience was pivotal in expanding my understanding of ecological research design and data management. I led the sample collection and protocol design for a project exploring ecological interactions across five Southern Californian ecosystems, emphasizing precision in data collection to minimize variance across sites. I was responsible for transforming raw field data into a meaningful story that could contribute to the scientific community’s understanding of these unique environments. My contribution to our publication in *Diversity* included not only statistical analysis but also creating detailed data visualizations that underscored key ecological patterns and implications. Presenting our findings at academic conferences reinforced my ability to communicate scientific data visually and verbally, allowing me to advocate for ecological preservation through accessible, evidence-based presentations.

-   **Robert J. Bernard Field Station Research**\
    At the Bernard Field Station, I engaged deeply with research on plant-soil feedback mechanisms and the ecological impact of native and invasive species, a project that aligned with my passion for biodiversity conservation. Working as a Restoration Technician, I conducted methodical data collection across 12 plots, analyzed microbial interactions, and tested soil nutrient levels. This experience brought home the importance of rigorous, repeatable research practices in ecological restoration, where every detail impacts our understanding of ecosystem health. Our team’s publication illuminated the complex interdependencies between plants, soil, and microbial communities, with my contributions to data visualization capturing the intricate relationships that promote ecosystem resilience. This project was instrumental in teaching me the real-world applications of ecological research, from laboratory techniques like DNA extraction to statistical methods that unveil hidden patterns in complex ecological datasets.

## Laboratory Experience

-   **Cell Chemistry and Cell Biology Lab Teaching Assistant**

As a Laboratory Teaching Assistant, I guided over 30 students in mastering core techniques of data analysis, visualization, and lab procedures. In this role, I emphasized precision and analytical thinking, helping students transform raw data into clear, scientifically sound reports. Leading hands-on sessions, I taught methods like western blotting, gel electrophoresis, and spectroscopy, instilling in students the importance of careful data handling. By fostering collaborative learning and critical problem-solving, I helped students build confidence in both their technical skills and their ability to interpret and present data—a foundation essential for future research and professional success.

**Skills:** Western blotting, SDS-Page, agarose gel electrophoresis, spectroscopy, PCR, DNA Sequencing, DNA extraction & purification, immunofluorescence, cell culturing, transfection and transformation, knockout techniques, co-immunoprecipitation, spectroscopy, distillation, enzyme kinetic assays

## Honors and Scholarships

Posse Foundation Full-Tuition Leadership Scholarship (2021 - 2025) 1for2 Foundation “Pay-it-Forward” Scholarship (**\$14,700** – 2021-2025) Institute for Study Abroad Scholarship—Melbourne, Australia: Academic Year (2023) Taco Bell Live Mas Video Scholarship (**\$10,000** – 2021; **\$10,000** – 2023) 2 Published Research Articles (2022 – 2023) Hispanic Scholarship Fund Scholar (2020 – 2023)

## 
