---
title: "Numbats Plots"
description: |
  TidyTuesday #1: Numbats in Australia Plots
author: Ana Jaramillo
date: September 19, 2024
format: html
execute:
  warning: false
  message: false
---

The data this week comes from the [Atlas of Living Australia](https://www.ala.org.au). Thanks to Di Cook for [preparing this week's dataset](https://github.com/numbats/numbats-tidytuesday)!

This plot visualizes the geographic coordinates of 787 sightings of the Numbat (Myrmecobius fasciatus), an iconic marsupial native to Australia. The data showcases the distribution of this species based on recorded observations.


```{r}
# Packages
library(tidyverse)
library(ggplot2)

# Data
numbats <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-03-07/numbats.csv')

# Filtering Data
numbats |>
  select(decimalLatitude, decimalLongitude, scientificName) |>
  filter(scientificName == "Myrmecobius fasciatus")

# Making Plots
ggplot(data = numbats, aes(x = decimalLatitude, y = decimalLongitude)) +
  geom_point() +
  labs(title = "Coordinates of 787 Numbats (Myrmecobius fasciatus)", x = "Coordinate Latitude", y = "Coordinate Longitude")
  
```

The x-axis represents latitude, and the y-axis represents longitude, offering a two-dimensional view of where Numbats have been documented. Numbats are known for their striking striped coats and their ecological role as termite specialists, making this species an essential part of Australia's biodiversity.

Through visualizations like this, we can better understand the spatial patterns of Numbat occurrences, which can be crucial for conservation efforts aimed at protecting their natural habitats. Their distribution is primarily concentrated in specific regions of Australia, which aligns with known ecological and environmental conditions favorable for this species.
